---
# Tests for this role


### Tests ###
- name: Verify java cmd is using v 1.7
  shell: java -version
  register: java_version
- assert:
    that:
      - "'1.7.0' in java_version.stderr"

# The role is run with a github oauth token passed in
# as github_oauth_token var value.
# This test confirms that the key being used will work
- name: ensure github token works
  shell:
    "github_post_status.py edx edx-platform
    dddac0b5dddf00c0950daf324e603e4935994954 success
    https://jenkins.testeng.edx.org/ \"Tests Passed\" \"CI Test Results\""
